openapi: 3.1.1
info:
  title: MarsRover API
  version: 1.0.0
  description: MarsRover API
servers:
  - url: http://localhost:8080
    description: Local server host.
paths:
  /health:
    get:
      summary: Returns the status of this service
      responses:
        "200":
          description: Success response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthCheckResponse"

components:
  schemas:
    HealthCheckResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          enum: ["ACTIVE"]
